In [17]:
import pandas as pd
import lmfit as lm
import numpy as np

In [2]:
data = pd.read_csv("~/Desktop/nyc_series.csv")

In [9]:
data.head()

local_date_id  rock_cookie_ginger_pre  rock_cookie_ginger_post  \
0       20180226                       0                       24   
1       20180225                       0                        7   
2       20180224                       0                       12   
3       20180223                       0                       18   
4       20180222                       0                       20   

   chelsea_cookie_ginger_pre  chelsea_cookie_ginger_post  \
0                          0                          11   
1                          0                           8   
2                          0                           7   
3                          0                           5   
4                          0                          11   

   dean_cookie_ginger_pre  dean_cookie_ginger_post  bryant_cookie_ginger_pre  \
0                       0                        5                         0   
1                       0                        7                         0   
2                       0                        8                         0   
3                       0                        3                         0   
4                       0                        2                         0   

   bryant_cookie_ginger_post  park_slope_cookie_ginger_pre  \
0                         10                             0   
1                          6                             0   
2                          6                             0   
3                          9                             0   
4                         13                             0   

             ...              dean_brownie_bite_pre  dean_brownie_bite_post  \
0            ...                                  0                       1   
1            ...                                  0                       5   
2            ...                                  0                       5   
3            ...                                  0                       1   
4            ...                                  0                       1   

   bryant_brownie_bite_pre  bryant_brownie_bite_post  \
0                        0                         8   
1                        0                         2   
2                        0                         5   
3                        0                        10   
4                        0                        10   

   park_slope_brownie_bite_pre  park_slope_brownie_bite_post  \
0                            0                             5   
1                            0                             6   
2                            0                            16   
3                            0                            11   
4                            0                             5   

   bushwick_brownie_bite_pre  bushwick_brownie_bite_post  \
0                          0                           2   
1                          0                           0   
2                          0                           1   
3                          0                           0   
4                          0                           1   

   clinton_brownie_bite_pre  clinton_brownie_bite_post  
0                         0                          1  
1                         0                          6  
2                         0                          7  
3                         0                          2  
4                         0                          3  

[5 rows x 127 columns]

In [5]:
mymatrix = data.as_matrix()

In [6]:
type(mymatrix)

numpy.ndarray

In [12]:
len(mymatrix.T)

127

In [16]:
desired = mymatrix.T[1]
desired

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0, 25, 16, 26, 31,  0, 23, 34, 34, 16, 22, 29,
       39, 36, 34, 23, 24, 13, 35, 48, 40, 32, 24, 13, 17, 30, 44, 34, 30,
       32, 16, 14, 27, 49, 36, 31, 41, 14, 11, 37, 35, 43, 28, 33, 15, 10,
       34, 40, 45, 38, 41, 12, 15, 40, 28, 37, 42, 38, 17, 13, 45, 43, 33,
       41, 27, 15, 15, 39, 39, 31, 35, 38, 13, 17, 32, 39, 34, 28, 38,  8,
       14, 34, 41, 35, 20,  8,  6,  2, 15, 20, 22, 26])

In [18]:
inputs = []
for i in np.arange(3,127,2):
    inputs.append(mymatrix.T[i])

In [42]:
myguess = np.matmul(desired, np.linalg.pinv(inputs))

In [44]:
result = np.matmul(myguess, inputs)

In [45]:
error = np.subtract(result, desired)

In [46]:
error

array([ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.  

In [48]:
myguess

array([-0.37725016, -0.29437415,  0.40512941,  0.49516293,  0.82185322,
       -0.09637998,  0.31179786, -0.01855175, -0.82845689,  0.52467256,
        0.43204727, -0.31680856, -0.42979358,  0.16885028, -0.07731241,
       -0.08184305,  0.35028771, -0.21241794,  0.28963031, -0.05809774,
        0.00761392, -0.12036139, -0.10130007, -0.67238115,  0.99019817,
       -0.7106329 ,  0.03465854,  0.97521808,  0.99917791, -0.0519349 ,
        0.02016795, -0.49417732, -0.62216956,  0.40448431,  0.08759398,
        0.47629979,  0.07164326, -0.06074976, -0.07801442, -0.05770701,
       -0.25304649, -0.09114291,  0.00437258,  0.12379849,  0.3445917 ,
       -0.34369139,  0.06778137,  0.16795766, -0.07029392,  0.13432227,
       -0.17068817, -0.01198337, -0.28958408, -0.04575358,  0.29704255,
        0.14578834, -0.02769597,  0.51208567, -0.41973686, -0.34127678,
        0.44565388,  0.17095573])