In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv("~/Desktop/nyc_series.csv")

In [3]:
data.head()

local_date_id  rock_cookie_ginger_pre  rock_cookie_ginger_post  \
0       20180226                       0                       24   
1       20180225                       0                        7   
2       20180224                       0                       12   
3       20180223                       0                       18   
4       20180222                       0                       20   

   chelsea_cookie_ginger_pre  chelsea_cookie_ginger_post  \
0                          0                          11   
1                          0                           8   
2                          0                           7   
3                          0                           5   
4                          0                          11   

   dean_cookie_ginger_pre  dean_cookie_ginger_post  bryant_cookie_ginger_pre  \
0                       0                        5                         0   
1                       0                        7                         0   
2                       0                        8                         0   
3                       0                        3                         0   
4                       0                        2                         0   

   bryant_cookie_ginger_post  park_slope_cookie_ginger_pre  \
0                         10                             0   
1                          6                             0   
2                          6                             0   
3                          9                             0   
4                         13                             0   

             ...              dean_brownie_bite_pre  dean_brownie_bite_post  \
0            ...                                  0                       1   
1            ...                                  0                       5   
2            ...                                  0                       5   
3            ...                                  0                       1   
4            ...                                  0                       1   

   bryant_brownie_bite_pre  bryant_brownie_bite_post  \
0                        0                         8   
1                        0                         2   
2                        0                         5   
3                        0                        10   
4                        0                        10   

   park_slope_brownie_bite_pre  park_slope_brownie_bite_post  \
0                            0                             5   
1                            0                             6   
2                            0                            16   
3                            0                            11   
4                            0                             5   

   bushwick_brownie_bite_pre  bushwick_brownie_bite_post  \
0                          0                           2   
1                          0                           0   
2                          0                           1   
3                          0                           0   
4                          0                           1   

   clinton_brownie_bite_pre  clinton_brownie_bite_post  
0                         0                          1  
1                         0                          6  
2                         0                          7  
3                         0                          2  
4                         0                          3  

[5 rows x 127 columns]

In [4]:
allcols = data.columns
c = []
for x in np.arange(2,len(allcols)):
    if 'cookie' in allcols[x]:
        if 'pre' in allcols[x]:
            c.append(x)

In [5]:
c

[3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27]

In [6]:
mymatrix = data.as_matrix()

In [7]:
desired = mymatrix.T[1]
desired

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0, 25, 16, 26, 31,  0, 23, 34, 34, 16, 22, 29,
       39, 36, 34, 23, 24, 13, 35, 48, 40, 32, 24, 13, 17, 30, 44, 34, 30,
       32, 16, 14, 27, 49, 36, 31, 41, 14, 11, 37, 35, 43, 28, 33, 15, 10,
       34, 40, 45, 38, 41, 12, 15, 40, 28, 37, 42, 38, 17, 13, 45, 43, 33,
       41, 27, 15, 15, 39, 39, 31, 35, 38, 13, 17, 32, 39, 34, 28, 38,  8,
       14, 34, 41, 35, 20,  8,  6,  2, 15, 20, 22, 26])

In [8]:
inputs = []
for i in c:
    inputs.append(mymatrix.T[i])

In [9]:
myguess = np.matmul(desired, np.linalg.pinv(inputs))

In [10]:
result = np.matmul(myguess, inputs)

In [11]:
error = np.subtract(result, desired)

In [12]:
error

array([  0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.  

In [13]:
myguess

array([ 0.04057927, -0.41092396,  0.43467523,  0.13353795,  0.86057485,
        0.08464691,  0.93847515,  0.11482575, -0.5460429 ,  0.92609917,
        0.18893508,  0.11392582, -0.29368813])